### ISSUE TITLE
ESR: passff 1.2 broken

### ISSUE THREAD

**Issue by dsommers** [passff/passff#309]
Used to run very well with former versions.  But now it's all a big mess after the 1.2 update.  I also updated the passff-host to 1.0.1.  And now neither passff 1.1 nor passff 1.2 works.  No matter which passff-host version being used.

Passff 1.2 gives a warning it cannot communicate with pass.  Passff 1.1 is just completely silent currently, with empty lists.  I can make it work by upgrading passff 1.1 to passff 1.2 **without** restarting Firefox.  But once restarting Firefox, its not working any more again.

I love pass and passff has been very valuable add-on to me.  So I surely hope this gets resolved quickly.  Please let me know if I can extract specific debug informations for you.

**Comment by tuxor1337** [comment]
I tried to replicate your problem in Firefox ESR and was NOT able to reproduce it. However, during testing I found an error message in the logs. Maybe this caused the strange behavior in your setup. Therefore, would you please test again with the most recent code from GitHub as described here: https://github.com/passff/passff/blob/master/docs/CONTRIBUTING.md#development?

**Comment by 5bentz** [comment]
#### Setup

Mozilla Firefox 52.7.2
Pass v1.6.5
Debian GNU/Linux 9 (stretch)
Linux 4.14.0-0.bpo.2-amd64 (backport)


#### With the old host program

...I cannot reproduce. PassFF 1.1 just works and PassFF 1.2 just fails with the error 'please check your host app'.

#### Let's try with the new host program: 1.0.1.

What works:
Install 1.2 from AMO with my current profile
Install 1.2 from AMO with a new profile
Latest version from github

What does not work:
PassFF 1.1 with my current profile.

#### Conclusion: I cannot reproduce the issue.

@dsommers
Are you sure the host app is correctly installed? Please could you doublecheck the path in `passff.json`.
I would try PassFF in a clean Firefox profile.
With `firefox -P`, you can easily create a second clean profile for testing and switch between profiles.

**Comment by tuxor1337** [comment]
@5bentz Thanks for testing! Regarding the "strange behavior" you describe: I remember a bug that was haunting Firefox for a long time, where closing Firefox would leave the binary in a dead state after an extension was installed temporarily using the `about:debugging` interface. Maybe that's what you experience with ESR. I don't know which version of Firefox fixed this eventually, but it's definitely fixed in 59.

**Comment by dsommers** [comment]
Sorry it took time to debug this ... but still hitting the same issue as before.  This is still broken for me.

Enabling debugging and all that, using git master for both passff and passff-host, loading the manifest.json file via about:debugging ... all I see in the "popup" window when clicking the "P" icon is:


     Connection to the host app failed or returned an unexpected result!
     
     Make sure you have the latest version of the PassFF host app installed by following the installation instructions on GitHub.
     [14:04:28] ls -> (-1) no error message

In the JavaScript console all I see are lines like these:

     [PassFF] Input search depth 0

I'm on RHEL 7.5 now

     $ rpm -q firefox
     firefox-52.7.3-1.el7_5.x86_64

(This is the Red Hat packaged Firefox ESR release)

And just to rule out something which could cause this to happen, I also disabled SELinux when running this debug session.

**Comment by tuxor1337** [comment]
Error code `(-1)` means that your host app is not installed correctly. How did you install the host app? Did you follow the instructions from the README in the passff-host repository? I.e.
```
$ cd ./src
$ make
$ cd ../bin/testing
$ ./install_host_app.sh --local [firefox|chrome|opera|chromium|vivaldi]
```

**Comment by dsommers** [comment]
Yepp.
Here's the passff.py file it installed: http://termbin.com/nxa1
And the passff.json file: http://termbin.com/cwsy

**Comment by tuxor1337** [comment]
Can you give the output of the debugging console that you reach via `about:debugging`, please? The output you quoted above seems to be the output from the web page JavaScript console which unfortunately is of no help in this case.

**Comment by tuxor1337** [comment]
Is this still an issue?

**Comment by dsommers** [comment]
It's been holiday season and too much work before and after, so haven't had a time to re-test.  However, Firefox got upgraded to 60.1.0 ESR one of these last days (still on RHEL 7), so need to look more carefully at everything once more.

**Comment by kugel-** [comment]
Doesn't work for me with Firefox 61. I also get the `[12:46:43] ls -> (-1) no error message` error when I visit a page with HTTP auth. For sites with login forms, it shows "No entries available".

I have passff 1.5.1 installed.

Below is the console output for a page with HTTP auth (note that the page is not publicly available):

```
[PassFF.background] Awaiting tab init... 16 https://gu.avm.de/ util.js:36:9
[PassFF.background] 0 matches for https://gu.avm.de/ util.js:36:9
[PassFF.background] Tab init done 16 https://gu.avm.de/ util.js:36:9
[PassFF.background] 0 matches for https://gu.avm.de/ util.js:36:9
[PassFF.background] onAuthRequired 2455 https://gu.avm.de/ util.js:36:9
[PassFF.background] 0 matches for https://gu.avm.de/ util.js:36:9
[PassFF.background] Open HTTP auth dialog util.js:36:9
[Show/hide message details.] win.gBrowser is undefined CustomizableWidgets.jsm:365
[PassFF.background] Awaiting tab init... 21 about:blank util.js:36:9
[PassFF.background] 0 matches for about:blank util.js:36:9
Sicherheitsfehler: Inhalt auf moz-extension://225a2839-408a-45bf-a593-560d9711ea28/ darf keine Daten von blob:null/86bb7795-3113-4059-a012-fd629e45ae1e laden.
[PassFF.background] 0 matches for about:blank util.js:36:9
Laden fehlgeschlagen für das <script> mit der Quelle "blob:null/86bb7795-3113-4059-a012-fd629e45ae1e". blank:1
[PassFF.background] Tab init done 21 about:blank util.js:36:9
[PassFF.background] Awaiting tab init... 21 moz-extension://b7e37fe1-739d-4858-9534-6a7172e6664c/content/itemPicker.html util.js:36:9
[PassFF.background] 0 matches for moz-extension://b7e37fe1-739d-4858-9534-6a7172e6664c/content/itemPicker.html util.js:36:9
[Show/hide message details.] Promise resolved while context is inactive
include.preload.js:751
Ignoring response to aborted listener for 25249
[Show/hide message details.] Promise rejected after context unloaded: Message manager disconnected
include.postload.js:766
[PassFF.background] Tab init done 21 moz-extension://b7e37fe1-739d-4858-9534-6a7172e6664c/content/itemPicker.html util.js:36:9
[PassFF.background] 0 matches for moz-extension://b7e37fe1-739d-4858-9534-6a7172e6664c/content/itemPicker.html util.js:36:9
[PassFF.background] Message Preferences.getBrowserCommand received in background util.js:36:9
[PassFF.background] Message Pass.loadItems received in background util.js:36:9
[Show/hide message details.] context.runSafeWithoutClone called while context is inactive ExtensionCommon.jsm:230
[PassFF.background] Message Menu.getLastState received in background util.js:36:9
[PassFF.background] Message Auth.getAuthForPopup received in background util.js:36:9
[PassFF.itemPicker] Create menu list 
Array []
util.js:36:9
[PassFF.itemPicker] Create children menu list 
Array []
 true util.js:36:9
[PassFF.background] Awaiting tab init... 21 moz-extension://b7e37fe1-739d-4858-9534-6a7172e6664c/content/itemPicker.html util.js:36:9
[PassFF.background] Tab init done 21 moz-extension://b7e37fe1-739d-4858-9534-6a7172e6664c/content/itemPicker.html util.js:36:9 
```

Here for a site with login form:

```
[PassFF.background] Awaiting tab init... 23 https://twitter.com/ util.js:36:9
[PassFF.background] 0 matches for https://twitter.com/ util.js:36:9
[PassFF.background] Tab init done 23 https://twitter.com/ util.js:36:9
[PassFF.background] Awaiting tab init... 23 https://twitter.com/ util.js:36:9
[PassFF.background] 0 matches for https://twitter.com/ util.js:36:9
[PassFF.background] Tab init done 23 https://twitter.com/ util.js:36:9
Content Security Policy: 'x-frame-options' wird wegen 'frame-ancestors'-Direktive ignoriert.
[PassFF.background] Awaiting tab init... 23 https://twitter.com/ util.js:36:9
[PassFF.background] 0 matches for https://twitter.com/ util.js:36:9
Error: WebExtension context not found! ExtensionParent.jsm:1009:13
[PassFF.background] Message Preferences.getBrowserCommand received in background util.js:36:9
[PassFF.background] Message Pass.loadItems received in background util.js:36:9
[Show/hide message details.] context.runSafeWithoutClone called while context is inactive ExtensionCommon.jsm:230
[PassFF.background] Message Preferences.getKeyboardShortcut received in background util.js:36:9
[PassFF.background] Tab init done 23 https://twitter.com/ util.js:36:9
Content Security Policy: 'x-frame-options' wird wegen 'frame-ancestors'-Direktive ignoriert.
[PassFF.background] Awaiting tab init... 23 https://twitter.com/ util.js:36:9
[PassFF.background] 0 matches for https://twitter.com/ util.js:36:9
[PassFF.background] Tab init done 23 https://twitter.com/ util.js:36:9
[PassFF.content] 0 matches for https://twitter.com/ util.js:36:9
[PassFF.content] Inject icon session[username_or_email] util.js:36:9
[PassFF.content] Inject icon session[password] util.js:36:9
[PassFF.background] Message Page.goToAutoFillPending received in background util.js:36:9
[PassFF.background] 0 matches for https://twitter.com/ util.js:36:9
Sicherheitsfehler: Inhalt auf https://twitter.com/ darf moz-extension://b7e37fe1-739d-4858-9534-6a7172e6664c/content/content-popup.html nicht laden oder verlinken.
[PassFF.background] Awaiting tab init... 23 https://twitter.com/ util.js:36:9
[PassFF.background] Tab init done 23 https://twitter.com/ util.js:36:9 

```

**Comment by tuxor1337** [comment]
@kugel- What does your problem have to do with this issue?

**Comment by dsommers** [comment]
I haven't had time to extract the full debug info ... but what @kugel- sees, is essentially the same I experience with firefox-60.1.0-4.el7_5.x86_64 on RHEL7.5

I simply have a bit too much to be able to follow up on this closely (and pass command line works well enough as a workaround)

**Comment by tuxor1337** [comment]
Ah, you mean that you also get error code `(-1)`. That means that you haven't installed the host app properly, but doesn't necessarily have anything to do with this issue. How did you install the host app? Did you follow the instructions from the README in the passff-host repository?

**Comment by dsommers** [comment]
I did, yes ... 

    $ ls -l ~/.mozilla/native-messaging-hosts 
    total 8
    -rw-r--r--. 1 user group  219 Aug  4 22:56 passff.json
    -rwxr-x--x. 1 user group 3192 Aug  4 22:56 passff.py

And `/usr/bin/python3` exists, and I can start passff.py on the command line without any failures appearing (need CTRL-C to stop running)

**Comment by kugel-** [comment]
So did I...
```

$ bash install_host_app.sh firefox
Python 3 executable located at /usr/bin/python3
Pass executable located at /usr/bin/pass
Installing Firefox host config
Native messaging host for Firefox has been installed to /home/tmartitz/.mozilla/native-messaging-hosts.


$ LANG=C ls -l ~/.mozilla/native-messaging-hosts
total 8
-rw-rw-r-- 1 tmartitz tmartitz  9 Aug 28 15:01 passff.json
-rwxrwxr-x 1 tmartitz tmartitz 18 Aug 28 15:01 passff.py

```

**Comment by dsommers** [comment]
Your passff.py and passff.json files looks quite tiny, @kugel-

**Comment by kugel-** [comment]
Err indeed.

```
$ cat ~/.mozilla/native-messaging-hosts/passff.json
Not Found
$ cat ~/.mozilla/native-messaging-hosts/passff.py
#!/usr/bin/python3
```

The real files also lack trailing newlines, I added them above for readability.

**Comment by dsommers** [comment]
Just reinstalled, to be 100% sure it's the latest code.

    passff-host/bin/testing (1.0.2) $ git log | head -n1
    commit 0982aeaf9657e463943921065a942adfa0541892 (HEAD, tag: 1.0.2)
    passff-host/bin/testing (1.0.2) $ bash ./install_host_app.sh --local firefox
    Python 3 executable located at /usr/bin/python3
    Pass executable located at /usr/bin/pass
    Installing Firefox host config
    Native messaging host for Firefox has been installed to /home/user/.mozilla/native-messaging-hosts.
    passff-host/bin/testing (1.0.2) $ ls -l /home/user/.mozilla/native-messaging-hosts/ 
    total 8
    -rw-r--r--. 1 user group  219 Aug 28 16:19 passff.json
    -rwxr-x--x. 1 user group 3192 Aug 28 16:19 passff.py

And your test:

     passff-host/bin/testing (1.0.2)  $ echo -e "\x02\x00\x00\x00[]" | ~/.mozilla/native-messaging-hosts/passff.py | tail -c +4; echo $?
     Traceback (most recent call last):
        File "/home/davids/.mozilla/native-messaging-hosts/passff.py", line 88, in <module>
          proc = subprocess.run(cmd, **proc_params)
    AttributeError: 'module' object has no attribute 'run'
    0

So subprocess seems to be the culprit.

**Comment by dsommers** [comment]
And some Python info:

    $ python3 --version ; rpm -q python34
    Python 3.4.8
    python34-3.4.8-2.el7.x86_64

**Comment by tuxor1337** [comment]
As pointed out in the README of passff-host we require Python >= 3.5

**Comment by dsommers** [comment]
I installed the python36 package and changed the shebang line to `#!/usr/bin/python3.6` and now it works fine.
